import type { Metadata } from "next";
import localFont from "next/font/local";
import { Toaster } from 'react-hot-toast';

import { Header } from "@/app/ui/sections/Header";
import { Footer } from "@/app/ui/sections/Footer";

import { UserContextProvider } from "@/context/user/UserContextProvider";
import { ProductsContextProvider } from "@/context/product/ProductsContextProvider";
import { CartContextProvider } from "@/context/cart/CartContextProvider";
import { ErrorBoundary } from "@/app/ui/components/ErrorBoundary";
import { CartSidebar } from "@/app/cart/ui/components/CartSidebar";
import { WishlistContextProvider } from "@/context/wishlist/WishlistContextProvider";

import "./globals.css";

const avenirNextCyrReg = localFont({
  src: "./fonts/AvenirNextCyr/AvenirNextCyr-Regular.ttf",
  variable: "--font-avenir-next-cyr",
  weight: "400",
});

const avenirNextCyrMed = localFont({
  src: "./fonts/AvenirNextCyr/AvenirNextCyr-Medium.ttf",
  variable: "--font-avenir-next-cyr",
  weight: "500",
});

const montserratAlternatesBold = localFont({
  src: "./fonts/MontserratAlternates/MontserratAlternates-Bold.ttf",
  variable: "--font-monsterrat-alternates",
  weight: "700",
});

const monsterratAlternatesReg = localFont({
  src: "./fonts/MontserratAlternates/MontserratAlternates-Regular.ttf",
  variable: "--font-monsterrat-alternates",
  weight: "400",
});

const montserratAlternatesMed = localFont({
  src: "./fonts/MontserratAlternates/MontserratAlternates-Medium.ttf",
  variable: "--font-monsterrat-alternates",
  weight: "500",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  auth,
}: Readonly<{
  children: React.ReactNode;
  auth: React.ReactNode;
}>) {
  return (
    <html lang="uk" className="h-full">
      <body
        className={
          `${avenirNextCyrReg.variable}
          ${avenirNextCyrMed.variable}
          ${montserratAlternatesBold.variable}
          ${monsterratAlternatesReg.variable}
          ${montserratAlternatesMed.variable}
          antialiased flex flex-col min-h-screen bg-secondary-50`
        }
      >
        <ErrorBoundary>
          <UserContextProvider>
            <ProductsContextProvider>
              <CartContextProvider>
                <WishlistContextProvider>
                  <>{auth}</>

                  <Header />

                  <main className="flex-grow">
                    {children}
                  </main>

                  <Footer />

                  <Toaster />
                  <CartSidebar />
                </WishlistContextProvider>
              </CartContextProvider>
            </ProductsContextProvider>
          </UserContextProvider>
        </ErrorBoundary>
      </body>
    </html>
  );
}
