import type { Metadata } from "next";
import localFont from "next/font/local";
import { Toaster } from 'react-hot-toast';

import { Header } from "@/app/ui/sections/Header";
import { Footer } from "@/app/ui/sections/Footer";

import { UserContextProvider } from "@/context/user/UserContextProvider";
import { ProductsContextProvider } from "@/context/product/ProductsContextProvider";
import { CartContextProvider } from "@/context/cart/CartContextProvider";
import { ErrorBoundary } from "@/app/ui/components/ErrorBoundary";
import { CartSidebar } from "@/app/cart/ui/components/CartSidebar";
import { WishlistContextProvider } from "@/context/wishlist/WishlistContextProvider";

import "./globals.css";

const avenirNextCyrReg = localFont({
  src: "./fonts/AvenirNextCyr/AvenirNextCyr-Regular.ttf",
  variable: "--font-avenir-next-cyr",
  weight: "400",
});

const avenirNextCyrMed = localFont({
  src: "./fonts/AvenirNextCyr/AvenirNextCyr-Medium.ttf",
  variable: "--font-avenir-next-cyr",
  weight: "500",
});

const montserratAlternatesBold = localFont({
  src: "./fonts/MontserratAlternates/MontserratAlternates-Bold.ttf",
  variable: "--font-monsterrat-alternates",
  weight: "700",
});

const monsterratAlternatesReg = localFont({
  src: "./fonts/MontserratAlternates/MontserratAlternates-Regular.ttf",
  variable: "--font-monsterrat-alternates",
  weight: "400",
});

const montserratAlternatesMed = localFont({
  src: "./fonts/MontserratAlternates/MontserratAlternates-Medium.ttf",
  variable: "--font-monsterrat-alternates",
  weight: "500",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  auth,
}: Readonly<{
  children: React.ReactNode;
  auth: React.ReactNode;
}>) {
  return (
    <html lang="uk" className="h-full overflow-x-clip">
      <body
        className={
          `${avenirNextCyrReg.variable}
          ${avenirNextCyrMed.variable}
          ${montserratAlternatesBold.variable}
          ${monsterratAlternatesReg.variable}
          ${montserratAlternatesMed.variable}
          antialiased flex flex-col min-h-screen`
        }
      >
        <ErrorBoundary>
          <UserContextProvider>
            <ProductsContextProvider>
              <CartContextProvider>
                <WishlistContextProvider>
                  <>{auth}</>

                  <Header />

                  <main className="flex-grow">
                    {children}
                  </main>

                  <Footer />

                  <Toaster
                    position="top-right"
                    reverseOrder={false}
                    gutter={12}
                    containerClassName="pointer-events-none z-[70] sm:mr-4 sm:mt-4"
                    toastOptions={{
                      duration: 2600,

                      style: {
                        background: '#ffffff',   // was 'transparent' — this hid your card
                        color: '#111827',        // Tailwind gray-900
                        boxShadow: 'none',       // let Tailwind shadow-card show through
                        padding: 0,
                      },

                      className: [
                        'pointer-events-auto relative overflow-hidden',
                        'flex items-start gap-3',
                        'w-[calc(100vw-1rem)] sm:w-auto sm:min-w-[320px] max-w-[420px]',
                        'px-4 py-3 sm:px-5 sm:py-4',
                        'rounded-2xl border border-secondary-100 bg-white shadow-card',
                        'text-sm text-gray-900 font-secondary',
                      ].join(' '),

                      success: {
                        duration: 2200,
                        icon: (
                          <span className="mt-0.5 inline-flex h-6 w-6 items-center justify-center rounded-full bg-primary/10 text-primary">
                            <svg viewBox="0 0 24 24" className="h-4 w-4" fill="none" stroke="currentColor" strokeWidth="2">
                              <path strokeLinecap="round" strokeLinejoin="round" d="M20 7L10 17l-4-4" />
                            </svg>
                          </span>
                        ),
                        className: 'before:absolute before:left-0 before:top-0 before:bottom-0 before:w-1.5 before:bg-primary/90',
                      },

                      error: {
                        duration: 3200,
                        icon: (
                          <span className="mt-0.5 inline-flex h-6 w-6 items-center justify-center rounded-full bg-rose-100 text-rose-600">
                            <svg viewBox="0 0 24 24" className="h-4 w-4" fill="none" stroke="currentColor" strokeWidth="2">
                              <path strokeLinecap="round" strokeLinejoin="round" d="M12 8v4m0 4h.01M12 3l9 9-9 9-9-9 9-9z" />
                            </svg>
                          </span>
                        ),
                        className: 'before:absolute before:left-0 before:top-0 before:bottom-0 before:w-1.5 before:bg-rose-500',
                      },

                      loading: {
                        icon: (
                          <span className="mt-0.5 inline-flex h-6 w-6 items-center justify-center rounded-full bg-primary/10 text-primary">
                            <svg viewBox="0 0 24 24" className="h-4 w-4 animate-spin" fill="none" stroke="currentColor" strokeWidth="2">
                              <circle cx="12" cy="12" r="9" className="opacity-25" />
                              <path d="M21 12a9 9 0 0 1-9 9" />
                            </svg>
                          </span>
                        ),
                        className: 'before:absolute before:left-0 before:top-0 before:bottom-0 before:w-1.5 before:bg-primary/70',
                      },
                    }}
                  />




                  <CartSidebar />
                </WishlistContextProvider>
              </CartContextProvider>
            </ProductsContextProvider>
          </UserContextProvider>
        </ErrorBoundary>
      </body>
    </html>
  );
}
